### ISSUE TITLE
Verificar como está sendo calculado a renda média para os dados da RAIS.

### ISSUE THREAD

**Issue by msbandrade** [DataViva/dataviva-api#102]
O cálculo de renda média exibida para as agregações seção e divisão estão sobre estimadas. Favor verificar como está sendo calculadas as médias e avaliar a possibilidade de correção. 
@litodaldegan @josianefaleiro 

![screenshot from 2019-02-19 15-40-12](https://user-images.githubusercontent.com/20859423/53039425-f8a9ef00-345d-11e9-895f-ef6e69d144b4.png)
![screenshot from 2019-02-19 15-39-56](https://user-images.githubusercontent.com/20859423/53039426-f8a9ef00-345d-11e9-8f0c-19936c456f64.png)

**Comment by litodaldegan** [comment]
@msbandrade 

Acredito que esteja sendo feito o agrupamento do dado por somatório. Para o caso relatado:

- Divisão - Comércio Varejista = **80821.87** somatório das rendas médias das classes (2264.25 + 2373.3 + 2627.64 + 2709.43 + 2087.86 + 1536.25 + 3529.22 + 2448.71 + 1887.98 + 1673.6 + 1889.17 + 2570.62 + 1625.02 + 1620.54 + 2220.52 + 1743.09 + 2038.94 + 2240.79 + 2936.19 + 2081.82 + 2255.09 + 2554.86 + 2317.85 + 2800.91 + 1733.09 + 1650.57 + 5089.81 + 2462.9 + 2369.78 + 1965.19 + 1591.32 + 2471.29 + 3810.37 + 1933.8 + 1710.1)

- Seção - Comércio
    $380 Mil BRL
 - + $**80,8** Mil BR Comércio Varejista
  
 - + $**281** Mil BRLComércio Atacadista
   
 - + $**17,8** Mil BRL Comércio de Veículos Automotores

**Comment by litodaldegan** [comment]
Duplicada em relação a https://github.com/DataViva/dataviva-site/issues/1666
