### ISSUE TITLE
Tratar exceção ao gravar dado no Redis

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-api#48]
A API faz uso do Redis para cacheamento das consultas realizadas. Porém, não há um tratamento de exceção para o caso de erro ao tentar salvar um novo dado no Redis. Deste modo, deverá ser implementado um tratamento de exceções para evitar erros na API quando não for possível gravar um dado no Redis.

Biblioteca de cacheamento utilizada: https://pythonhosted.org/Flask-Cache/
Versão atual do Redis em produção: 2.8.4

**Comment by diogolundberg** [comment]
Isso fica obsoleto a partir da implementação do #55
