### ISSUE TITLE
Criar flag para produção

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-api#50]
Ao selecionar dados através da [API](https://github.com/DataViva/dataviva-api/blob/master/app/apis/datasets_api.py), o ambiente deverá ser considerado para filtrar estes dados:
- Criar uma coluna em todas as tabelas referente ao ambiente que os dados estarão disponíveis.
  - O nome desta coluna pode ser ENV por exemplo.
- Em produção, somente os dados marcados como "Production".
- Os outros ambientes podem considerar os dados de produção e todos os outros que estarão ainda em homologação.

**Comment by diogolundberg** [comment]
Implementado em #b40f21cf
