### ISSUE TITLE
[Staging] Verificar erro em endpoint

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-api#87]
Verificar erro ao retornar dados no endpoint do ambiente de homologação. Erro só foi identificado para o município São Paulo (3550308). Segue endereço do endpoint:

http://staging.api.dataviva.info/secex/month/year/product_section/product/?type=export&municipality=3550308

**Comment by diogolundberg** [comment]
Não consegui reproduzir, está funcionando
