### ISSUE TITLE
Estudar solução para cache

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-api#89]
Dod:
- Analisar o uso de memória necessário
- Analisar o custo do ElastiCache vs ec2

**Comment by litodaldegan** [comment]
Avaliação das soluções levantadas realizada.

[Avaliação Redis (cache) 20180615.pdf](https://github.com/DataViva/dataviva-api/files/2107413/Avaliacao.Redis.cache.20180615.pdf)

**Comment by litodaldegan** [comment]
Pequena avaliação de custos para opções de dimensionamento de máquina e cache: 
[Custo de recurso.pdf](https://github.com/DataViva/dataviva-api/files/2116358/Custo.de.recurso.pdf)
