### ISSUE TITLE
Configuração de TTL e Timeout

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-api#90]
Dod:
- Configurar o timeout do SQLAlchemy/nginx de forma que requisições demoradas não apresentem timeout
- Configurar TTL do redis de forma que o cache seja melhor preservado.

**Comment by rafaelsmedina** [comment]
A requisição que estava demorando está tão grande que trava o computador quando consegue completar, mesmo com o timeout do nginx bem alto. Portanto, não compensa aumentar esse valor.

**Comment by diogolundberg** [comment]
Não concordo que isso esteja solucionado. Precisamos pelo menos testar isso numa máquina maior pra ver se é este o problema mesmo.

**Comment by rafaelsmedina** [comment]
Uma sugestão é que a página do brasil não busque o nome de todas as escolas, apenas os valores agregados. 
O arquivo é muito grande e chega a travar o computador.

**Comment by diogolundberg** [comment]
> Uma sugestão é que a página do brasil não busque o nome de todas as escolas
O objetivo desta issue é configurarmos o servidor para evitar o timeout em requisições demoradas.

Não deveríamos focar em outro problema que é "repensar na forma de visualização dos dados do Brasil".

Antes de concluir sobre este tópico, ou se vamos ou não aumentar o tempo de timeout, precisamos saber melhor que arquivo é este que você está falando e aonde está sobrecarregando a máquina.

**Comment by diogolundberg** [comment]
http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine.params.case_sensitive

**Comment by rafaelsmedina** [comment]
Para a API, foram alterados o timeout do gunicorn, utilizando o comando:
```
--timeout 900 --graceful-timeout 900
```

e também o timeout do nginx, utilizando os comandos:
```
proxy_connect_timeout 900;
proxy_send_timeout 900;
proxy_read_timeout 900;
send_timeout 900;
fastcgi_read_timeout 900;
```
Dessa maneira, a API de produção consegue retornar buscas grandes, como a busca por escolas.
