### ISSUE TITLE
Otimizar Elasticache 

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-api#91]
Dod:
- Configurar TTL menos prioritário para legacy/site/staging
- Aumentar o tamanho do elasticache

**Comment by litodaldegan** [comment]
## Descrição:
Visto que o _Redis_ (do _Elasticache_) é um recurso compartilhado entre cinco serviços, é importante que o tempo de vida dos dados salvos (_TTL_ - _time to life_) seja otimizado de forma a obter o melhor desempenho da plataforma DataViva. Para isto, os dados cacheados da API de produção devem ser priorizados em relação ao dados de cache do site(_production_, _legacy_ e _staging_) como também em relação ao dados da API de staging.
É importante frisar, que um dado por ser removido em duas situações:
- Seu tempo de vida chegou ao fim;
- A memória do Redis chegou ao seu limite e ele substituir os dados com menor tempo de vida.
Desta forma, a definição de tempo de vida das chaves deve levar em consideração a importância de que algumas chaves devem ser removidas depois de um tempo (dados que tem uma chance remota de reutilizados) e a chaves novas devem ser mantidas por pelo menos por um período mínimo. Ou seja, deve ser configurado de forma que um recurso não domine toda a utilização do cache, fazendo com que os dados dos outros serviços sejam apagados pouco tempo depois de serem criados.
## Política de remoção
O redis versão 2.8.24 (usada atualmente) do elasticache tem por padrão a política de remoção de chaves _volatile-lru_. Esta política, quando a memória do redis atinge seu máximo de espaço disponível, remove chaves que não foram usadas pelo maior período (_LRU - Least Recently Used_). Mecanismo que já atende a necessidade de evitar a remoção de chaves que foram criadas recentemente mas fere um pouco a necessidade de priorizar as chaves com maior tempo de vida (_TTL_). Porém, visto que alguns dados a serem priorizado podem ser também muito pouco utilizados, este regime deve atender bem ao propósito.
## Tempo de vida (_TTL_)
Para as configurações de tempo de vida dos dados cacheados para cada um dos serviços, segue uma proposta de reconfiguração:

Recurso | _TTL_ atual | _TTL_ proposto |
------------|--------------|----------------|
api-production | 60000000 s | 7884000 s (três meses) |
api-staging | 60000000 s | 604800 s (uma semana) |
site-production | 60000000 s | 2592000 s (trinta dias) |
site-staging | 60000000 s | 14400 s (quatro horas) |
legacy | 60000000 s | 604800 s (uma semana) |
metadado-production | indefinido | indefinido |
metadado-staging | indefinido | indefinido |
## Alteração do máximo de memória
Para poder suportar o uso por cinco serviços diferentes, a instância do _Redis Elasticache_ foi alterada de _cache.t2.small_ (memória: 1,55GiB) para _cache.t2.medium_ (memória: 3,22GiB).
